main: com.prox.integration.Main
name: ProxIntegration
version: 1.6
author: jtsalisbury
description: Provides integration with Prox
api-version: 1.18
commands:
  settoken:
    description: Set the Prox authorization tokens
    usage: /settoken [token]
    permission: prox.manage
    permission-message: You don't have the prox.manage permission.

  clearqueue:
    description: Clears any queued messages
    usage: /clearqueue
    permission: prox.manage
    permission-message: You don't have the prox.manage permission.

  reconnect:
    description: Disconnects the current socket and attempts to reconnect
    usage: /reconnect
    permission: prox.manage
    permission-message: You don't have the prox.manage permission.

  dump:
    description: Prints active debugging information to the server console
    usage: /dump
    permission: prox.manage
    permission-message: You don't have the prox.manage permission.

permissions:
  prox.manage:
    description: Allows for management of Prox
    default: op